name: alchemyplatform/rundler
on: [dispatch_worflow]

jobs:
  bundler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          repository: alchemyplatform/rundler
          path: deps/alchemyplatform/rundler

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          path: deps/alchemyplatform/rundler
          file: alchemyplatform/rundler/Dockerfile
          push: true
          tags: 5afe/erc4337-bundlers-alchemyplatform-rundler:latest
