name: alchemyplatform/rundler
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          repository: alchemyplatform/rundler
          path: deps/alchemyplatform/rundler

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: deps/alchemyplatform/rundler
          file: deps/alchemyplatform/rundler/Dockerfile
          push: true
          tags: ghcr.io/5afe/erc4337-bundlers-alchemyplatform-rundler:latest
