name: eth-infinithsm/bundler
on: workflow_dispatch

jobs:
  bundler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: eth-infinitism/bundler
          ref: v0.6.0
          path: deps/eth-infinitism/bundler

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: deps/eth-infinitism/bundler
          file: bundler/Dockerfile
          push: true
          tags: ghcr.io/5afe/erc4337-bundlers-eth-infinitism-bundler:latest
