name: pimlicolabs/alto
on: [dispatch_worflow]

jobs:
  bundler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: pimlicolabs/alto
          path: deps/pimlicolabs/alto

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          path: deps/pimlicolabs/alto
          file: pimlicolabs/alto/Dockerfile
          push: true
          tags: 5afe/erc4337-bundlers-pimlicolabs-alto:latest
